services:
  dev-db:
    image: "postgres:13"
    ports:
      - 8080:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - fullstack
networks:
  fullstack:
